export const FALLBACK_TICKER = 'AAPL';

export const MODEL_METADATA = {
  model: 'RF v0.1',
  auc: '0.62',
  training: '2018-2024',
  stocks: '503',
};

export const MARKET_STRIP = [
  { symbol: 'SPX', value: '5,241.53', change: '+0.12%', up: true },
  { symbol: 'NDX', value: '18,321.10', change: '+0.34%', up: true },
  { symbol: 'VIX', value: '13.12', change: '-2.11%', up: false },
  { symbol: '10YR', value: '4.21%', change: '+0.03%', up: true },
  { symbol: 'DXY', value: '104.28', change: '-0.18%', up: false },
];

export const TICKER_TAPE = [
  { symbol: 'AAPL', price: '$182.41', change: '+0.68%', up: true },
  { symbol: 'MSFT', price: '$415.32', change: '-0.50%', up: false },
  { symbol: 'NVDA', price: '$894.52', change: '-1.33%', up: false },
  { symbol: 'GOOGL', price: '$148.63', change: '+0.44%', up: true },
  { symbol: 'META', price: '$496.88', change: '+0.92%', up: true },
  { symbol: 'AMZN', price: '$182.06', change: '+0.29%', up: true },
  { symbol: 'TSLA', price: '$175.22', change: '-0.84%', up: false },
  { symbol: 'BRK.B', price: '$420.18', change: '+0.14%', up: true },
  { symbol: 'JPM', price: '$198.77', change: '-0.09%', up: false },
  { symbol: 'V', price: '$281.64', change: '+0.31%', up: true },
  { symbol: 'AMD', price: '$180.11', change: '-0.22%', up: false },
  { symbol: 'INTC', price: '$43.02', change: '+0.40%', up: true },
  { symbol: 'NFLX', price: '$638.19', change: '+0.61%', up: true },
  { symbol: 'TSM', price: '$144.08', change: '+0.27%', up: true },
  { symbol: 'CRM', price: '$301.74', change: '-0.17%', up: false },
  { symbol: 'ORCL', price: '$127.59', change: '+0.22%', up: true },
];

const STOCK_LIST = [
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Technology Hardware',
    price: '182.41',
    priceChange: '+1.24',
    priceChangePercent: '+0.68%',
    up: true,
    score: 31,
    verdict: 'Moderately Undervalued',
    ci: [24, 31, 38],
    ciLabel: 'High Confidence · σ = 1.2',
    confluenceType: 'strong',
    confluenceDesc: 'Fundamental Score 31 · Model confidence high',
    subs: [
      { key: 'V', name: 'Valuation', value: 28 },
      { key: 'Q', name: 'Quality', value: 18 },
      { key: 'M', name: 'Momentum', value: 35 },
      { key: 'S', name: 'Sentiment', value: 42 },
    ],
    shap: [
      { feature: 'ROIC', value: '+0.18', rawValue: 0.18, positive: true },
      {
        feature: 'EV/EBITDA',
        value: '+0.12',
        rawValue: 0.12,
        positive: true,
      },
      {
        feature: 'RevGrowth',
        value: '+0.08',
        rawValue: 0.08,
        positive: true,
      },
      { feature: 'PB', value: '-0.09', rawValue: 0.09, positive: false },
      {
        feature: 'GrossMargin',
        value: '-0.06',
        rawValue: 0.06,
        positive: false,
      },
    ],
    metrics: [
      { name: 'P/E', value: '28.4×', vsSector: '23.1×', better: false },
      {
        name: 'EV/EBITDA',
        value: '22.1×',
        vsSector: '18.4×',
        better: false,
      },
      { name: 'ROIC', value: '47.2%', vsSector: '15.8%', better: true },
      {
        name: 'Gross Margin',
        value: '45.9%',
        vsSector: '38.2%',
        better: true,
      },
      { name: 'FCF Yield', value: '3.8%', vsSector: '2.9%', better: true },
      {
        name: 'Rev Growth',
        value: '+8.1%',
        vsSector: '+6.2%',
        better: true,
      },
    ],
    chatInit:
      'AAPL scores 31 — Moderately Undervalued. ROIC is the primary driver at +0.18. What would you like to explore?',
    responses: {
      why: 'AAPL screens as moderately undervalued because quality and capital efficiency offset the richer multiple profile. ROIC, EV/EBITDA, and revenue growth lift the model output more than PB and gross margin drag it back.',
      risk: 'Key risks for large-cap hardware are slower upgrade cycles, tighter Services attach, China demand volatility, and any margin compression if the product mix shifts downmarket.',
      shap: 'SHAP decomposes the model output into feature-level contributions. Positive values push the score toward opportunity, while negative values reflect richer valuation or weaker operating signals.',
      confidence: 'The MAPIE interval of [24 - 38] is relatively tight, so the model is signaling high confidence around the 31 score. Sigma at 1.2 means dispersion across conformal estimates is low for this setup.',
      auc: 'AUC of 0.62 is useful but not magical. It means the model is directionally better than chance on out-of-sample ranking, but it still needs human judgment and should not be treated as a standalone buy signal.',
    },
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    sector: 'Software Infrastructure',
    price: '415.32',
    priceChange: '-2.10',
    priceChangePercent: '-0.50%',
    up: false,
    score: 44,
    verdict: 'Fairly Valued',
    ci: [37, 44, 52],
    ciLabel: 'Moderate Confidence · σ = 1.8',
    confluenceType: 'neutral',
    confluenceDesc: 'Fundamental Score 44 · Balance of quality and valuation',
    subs: [
      { key: 'V', name: 'Valuation', value: 48 },
      { key: 'Q', name: 'Quality', value: 22 },
      { key: 'M', name: 'Momentum', value: 41 },
      { key: 'S', name: 'Sentiment', value: 38 },
    ],
    shap: [
      { feature: 'ROIC', value: '+0.14', rawValue: 0.14, positive: true },
      {
        feature: 'RevGrowth',
        value: '+0.11',
        rawValue: 0.11,
        positive: true,
      },
      { feature: 'PE', value: '-0.13', rawValue: 0.13, positive: false },
      {
        feature: 'EV/EBITDA',
        value: '-0.09',
        rawValue: 0.09,
        positive: false,
      },
      {
        feature: 'FCFYield',
        value: '-0.04',
        rawValue: 0.04,
        positive: false,
      },
    ],
    metrics: [
      { name: 'P/E', value: '35.8×', vsSector: '23.1×', better: false },
      {
        name: 'EV/EBITDA',
        value: '24.7×',
        vsSector: '18.4×',
        better: false,
      },
      { name: 'ROIC', value: '31.4%', vsSector: '15.8%', better: true },
      {
        name: 'Gross Margin',
        value: '69.3%',
        vsSector: '38.2%',
        better: true,
      },
      { name: 'FCF Yield', value: '2.7%', vsSector: '2.9%', better: false },
      {
        name: 'Rev Growth',
        value: '+15.4%',
        vsSector: '+6.2%',
        better: true,
      },
    ],
    chatInit:
      'MSFT scores 44 — Fairly Valued. ROIC is the primary driver at +0.14. What would you like to explore?',
    responses: {
      why: 'MSFT lands near fair value because exceptional quality metrics are being offset by a premium valuation stack. ROIC and revenue growth are constructive, but P/E and EV/EBITDA remain the main headwinds.',
      risk: 'Core software risks include Azure optimization, enterprise budget fatigue, AI infrastructure payback, and multiple compression if growth expectations cool before margins expand further.',
      shap: 'SHAP shows which features move the prediction most for this specific name. Here the model likes Microsoft’s operating quality, but it discounts the stock for expensive headline multiples.',
      confidence: 'The [37 - 52] range is wider than AAPL’s, so confidence is moderate rather than high. MAPIE is telling us there is more uncertainty around where fair value should sit for this profile.',
      auc: 'AUC at 0.62 means the model is a modest ranking engine, not a crystal ball. It can help prioritize research, but the spread between signal and noise is still narrow enough that fundamentals matter a lot.',
    },
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'Semiconductors',
    price: '894.52',
    priceChange: '-12.10',
    priceChangePercent: '-1.33%',
    up: false,
    score: 67,
    verdict: 'Moderately Overvalued',
    ci: [58, 67, 76],
    ciLabel: 'Moderate Confidence · σ = 2.4',
    confluenceType: 'caution',
    confluenceDesc: 'Fundamental Score 67 · Valuation stretch dominates',
    subs: [
      { key: 'V', name: 'Valuation', value: 78 },
      { key: 'Q', name: 'Quality', value: 31 },
      { key: 'M', name: 'Momentum', value: 52 },
      { key: 'S', name: 'Sentiment', value: 44 },
    ],
    shap: [
      { feature: 'PE', value: '-0.22', rawValue: 0.22, positive: false },
      {
        feature: 'EV/EBITDA',
        value: '-0.16',
        rawValue: 0.16,
        positive: false,
      },
      { feature: 'PB', value: '-0.11', rawValue: 0.11, positive: false },
      { feature: 'ROIC', value: '+0.15', rawValue: 0.15, positive: true },
      {
        feature: 'RevGrowth',
        value: '+0.12',
        rawValue: 0.12,
        positive: true,
      },
    ],
    metrics: [
      { name: 'P/E', value: '72.1×', vsSector: '24.5×', better: false },
      {
        name: 'EV/EBITDA',
        value: '51.8×',
        vsSector: '17.3×',
        better: false,
      },
      { name: 'ROIC', value: '82.4%', vsSector: '12.1%', better: true },
      {
        name: 'Gross Margin',
        value: '74.9%',
        vsSector: '48.7%',
        better: true,
      },
      { name: 'FCF Yield', value: '1.6%', vsSector: '3.1%', better: false },
      {
        name: 'Rev Growth',
        value: '+88.4%',
        vsSector: '+12.8%',
        better: true,
      },
    ],
    chatInit:
      'NVDA scores 67 — Moderately Overvalued. PE is the primary driver at -0.22. What would you like to explore?',
    responses: {
      why: 'NVDA has elite growth and returns, but the model still leans toward overvaluation because P/E, EV/EBITDA, and PB are all extremely stretched versus semiconductor medians.',
      risk: 'Semiconductor risks center on hyperscaler digestion, export controls, competitive inference pricing, and any slowing in AI capex conversion after the current deployment wave.',
      shap: 'SHAP is helpful here because it separates great business quality from expensive entry price. NVIDIA’s positives are strong, but the negative valuation contributions are even larger in aggregate.',
      confidence: 'The MAPIE band of [58 - 76] is wide enough to signal moderate confidence only. The model is fairly sure valuation is rich, but less certain about how quickly that richness should mean-revert.',
      auc: 'A 0.62 AUC is honest, not heroic. It indicates useful signal for ranking names, but on high-volatility stocks like NVDA, the residual uncertainty is still large and timing remains difficult.',
    },
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'Internet Services',
    price: '148.63',
    priceChange: '+0.65',
    priceChangePercent: '+0.44%',
    up: true,
    score: 36,
    verdict: 'Fairly Valued',
    ci: [29, 36, 43],
    ciLabel: 'Moderate Confidence · σ = 1.6',
    confluenceType: 'neutral',
    confluenceDesc: 'Fundamental Score 36 · Slight discount to fair value',
    subs: [
      { key: 'V', name: 'Valuation', value: 34 },
      { key: 'Q', name: 'Quality', value: 24 },
      { key: 'M', name: 'Momentum', value: 40 },
      { key: 'S', name: 'Sentiment', value: 45 },
    ],
    shap: [
      { feature: 'ROIC', value: '+0.10', rawValue: 0.1, positive: true },
      {
        feature: 'FCFYield',
        value: '+0.07',
        rawValue: 0.07,
        positive: true,
      },
      { feature: 'PE', value: '-0.08', rawValue: 0.08, positive: false },
      {
        feature: 'RevGrowth',
        value: '+0.05',
        rawValue: 0.05,
        positive: true,
      },
      {
        feature: 'GrossMargin',
        value: '-0.04',
        rawValue: 0.04,
        positive: false,
      },
    ],
    metrics: [
      { name: 'P/E', value: '24.8×', vsSector: '23.1×', better: false },
      {
        name: 'EV/EBITDA',
        value: '14.7×',
        vsSector: '18.4×',
        better: true,
      },
      { name: 'ROIC', value: '28.1%', vsSector: '15.8%', better: true },
      {
        name: 'Gross Margin',
        value: '56.7%',
        vsSector: '38.2%',
        better: true,
      },
      { name: 'FCF Yield', value: '4.2%', vsSector: '2.9%', better: true },
      {
        name: 'Rev Growth',
        value: '+11.5%',
        vsSector: '+6.2%',
        better: true,
      },
    ],
    chatInit:
      'GOOGL scores 36 — Fairly Valued. ROIC is the primary driver at +0.10. What would you like to explore?',
    responses: {
      why: 'Alphabet sits close to fair value because cash generation and returns are attractive, but the model sees enough multiple support already reflected in the price.',
      risk: 'Internet platform risks include search share pressure, cloud margin execution, regulatory remedies, and ad demand sensitivity to macro slowdowns.',
      shap: 'SHAP breaks the model into name-specific pushes and pulls. For GOOGL, ROIC and free-cash-flow yield help, while a still-premium P/E and margin normalization cap upside.',
      confidence: 'The [29 - 43] MAPIE band implies moderate confidence. The model sees a relatively balanced setup rather than a deeply asymmetric opportunity or warning.',
      auc: 'AUC of 0.62 is enough to guide research triage, but not enough to skip the thesis work. With a neutral score like 36, qualitative views can easily overwhelm the statistical edge.',
    },
  },
  {
    ticker: 'META',
    name: 'Meta Platforms, Inc.',
    sector: 'Interactive Media',
    price: '496.88',
    priceChange: '+4.55',
    priceChangePercent: '+0.92%',
    up: true,
    score: 29,
    verdict: 'Moderately Undervalued',
    ci: [22, 29, 37],
    ciLabel: 'High Confidence · σ = 1.3',
    confluenceType: 'strong',
    confluenceDesc: 'Fundamental Score 29 · Model confidence high',
    subs: [
      { key: 'V', name: 'Valuation', value: 26 },
      { key: 'Q', name: 'Quality', value: 19 },
      { key: 'M', name: 'Momentum', value: 33 },
      { key: 'S', name: 'Sentiment', value: 41 },
    ],
    shap: [
      { feature: 'ROIC', value: '+0.16', rawValue: 0.16, positive: true },
      {
        feature: 'FCFYield',
        value: '+0.10',
        rawValue: 0.1,
        positive: true,
      },
      {
        feature: 'RevGrowth',
        value: '+0.07',
        rawValue: 0.07,
        positive: true,
      },
      { feature: 'PE', value: '-0.06', rawValue: 0.06, positive: false },
      {
        feature: 'GrossMargin',
        value: '+0.05',
        rawValue: 0.05,
        positive: true,
      },
    ],
    metrics: [
      { name: 'P/E', value: '24.1×', vsSector: '23.1×', better: false },
      {
        name: 'EV/EBITDA',
        value: '15.2×',
        vsSector: '18.4×',
        better: true,
      },
      { name: 'ROIC', value: '34.8%', vsSector: '15.8%', better: true },
      {
        name: 'Gross Margin',
        value: '81.4%',
        vsSector: '38.2%',
        better: true,
      },
      { name: 'FCF Yield', value: '4.4%', vsSector: '2.9%', better: true },
      {
        name: 'Rev Growth',
        value: '+19.6%',
        vsSector: '+6.2%',
        better: true,
      },
    ],
    chatInit:
      'META scores 29 — Moderately Undervalued. ROIC is the primary driver at +0.16. What would you like to explore?',
    responses: {
      why: 'META screens as moderately undervalued because strong returns, cash generation, and growth all combine to outweigh only mildly rich headline multiples.',
      risk: 'Interactive media risks include ad pricing volatility, heavier AI infrastructure spend, regulatory restrictions, and user engagement shifts toward lower-monetization surfaces.',
      shap: 'SHAP explains the forecast by translating model output into additive feature effects. For META, the quality and cash-flow factors are doing most of the work in the current score.',
      confidence: 'The [22 - 37] interval is fairly tight, so MAPIE is signaling high confidence for this name. The distribution is still not certainty, but it is more stable than the broader neutral names.',
      auc: 'At 0.62 AUC the model is meaningfully informative, but it should still be treated as a ranking input rather than an execution rule. That is especially true when sector narratives are moving quickly.',
    },
  },
];

export const STOCKS = Object.fromEntries(
  STOCK_LIST.map((stock) => [stock.ticker, stock]),
);
